{% set name = "loguru-mypy" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/loguru-mypy-{{ version }}.tar.gz
  sha256: 1f1767d7737f1825295ce147f7e751f91837f5759b3c2f41801adc65691aeed4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setupmeta
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - loguru_mypy
  commands:
    - pip check
  requires:
    - pip
    - mypy
    - python {{ python_min }}

about:
  home: https://github.com/kornicameister/loguru-mypy
  summary: mypy plugin for loguru
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
